### ISSUE TITLE
Logs incorrect?

### ISSUE THREAD

**Issue by Erisfiregamer1** [Picoseconds/sanctuary#24]
I have this hosted on Glitch.
However, the logs keep saying that it is hosting on localhost:3000
I want it to host to oasis-template.glitch.me
does it host there too? If so, how do you fix the logs so it says it right?

**Comment by CorruptedAI** [comment]
It hosts on oasis-template.glitch.me, even if the terminal says it's hosting on localhost:3000. Online-hosters remove the pain of configuring the port as they do it themselves. If you're wondering why you can't connect to oasis-template.glitch.me directly is because you must request to open a websocket. This is done via the userscript provided in the readme file. If you do not want to use a userscript to port client-side, you must create another glitch.me project that automates this process.

**Comment by Picoseconds** [comment]
@Erisfiregamer1 The logs come from `oasis-template.glitch.me` so it is `localhost` for itself. It is hosting on the correct location and the logs do not need to be fixed.
